### ISSUE TITLE
Issue with Seq iterators

### ISSUE THREAD

**Issue by KnowledgeGarden** [allenai/openie-standalone#29]
In Eclipse Neon Java 1.8 Scala 2.11 (and 2.12) I borrowed a demo code from
https://raw.githubusercontent.com/yiboyang/openie-server/master/Demo.java
and am compiling that against openie-4.1.jar

Specific code snippet:

        OpenIE openIE = new OpenIE(new ClearParser(new ClearPostagger(new ClearTokenizer(ClearTokenizer.defaultModelUrl()))),
                new ClearSrl(), false);
        Seq<Instance> extractions = openIE.extract("U.S. president Barack Obama gave his inaugural address on January 20, 2013.");
        Iterator<Instance> iterator = extractions.iterator();

Eclipse compiler is unhappy with extractions.iterator();
"The method iterator() is ambiguous for the type Seq<Instance>"

As a test, I added scala-library-2.12.2.jar to the classpath with no change.

Overall, I am looking for ways to use OpenIE as a service in a larger project.

Thanks in advance for advice or comments.

**Comment by KnowledgeGarden** [comment]
I managed to solve this problem; it might have been an eclipse problem, but  switching to the latest Eclipse Oxygen made no change. Instead, I went around Scala and shifted to Java collections and iterators with this:

`        OpenIE openIE = new OpenIE(new ClearParser(new ClearPostagger(new ClearTokenizer(ClearTokenizer.defaultModelUrl()))),
                new ClearSrl(), false);

        Seq<Instance> extractions = openIE.extract("U.S. president Barack Obama gave his inaugural address on January 20, 2013.");
        List<Instance> ext = JavaConversions.seqAsJavaList(extractions);
        Iterator<Instance> iterator = ext.iterator();`

That got the platform to compile and to run. I can say that the compile error (this issue) is now resolved, and will close this. I cannot say that the code runs because, while the program loaded a lot of models and features while running, that is, loading parsers taggers, etc, it blew up with this error message on the top line constructing OpenIE. That will be my next project, possibly (I hope not) a new issue:
Exception in thread "main" java.lang.NoSuchMethodError: scala.Predef$.refArrayOps([Ljava/lang/Object;)Lscala/collection/mutable/ArrayOps;
	at edu.knowitall.chunkedextractor.Relnoun$AppositiveExtractor.<init>(Relnoun.scala:305)
	at edu.knowitall.chunkedextractor.Relnoun.<init>(Relnoun.scala:21)
	at edu.knowitall.openie.OpenIE.<init>(OpenIE.scala:40)
	at org.topicquests.opensherlock.openie.Demo.main(Demo.java:29)
